server:
  port: 8088

spring:
  application:
     name: notification-service

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: notification-group
    topics:
      new-topic: NEW
      rejected-topic: REJECTED
      withdrawn-topic: WITHDRAWN
      accepted-topic: ACCEPTED
      email-verification: email-verification
      password-reset: password-reset
      job-alert: job-alert

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5442}/notificationdb
    username: ${DB_USERNAME:notifuser}
    password: ${DB_PASSWORD:notifpass}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:nikitavolzin55@gmail.com}
    password: ${MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  app:
    notifications:
      templates:
        NEW_APPLICATION:
          subject: "Новый отклик на вакансию"
          body: "На вашу вакансию '%s' пришел новый отклик."
        REJECTED_APPLICATION:
          subject: "Статус вашей заявки изменен"
          body: "Уважаемый кандидат, ваша заявка на вакансию '%s' была отклонена."
        WITHDRAWN_APPLICATION:
          subject: "Кандидат отозвал заявку"
          body: "Заявка на вакансию '%s' была отозвана отправителем."
        ACCEPTED_APPLICATION:
          subject: "Ваша заявка принята!"
          body: "Поздравляем! Ваша заявка на вакансию '%s' была принята."

logging:
  level:
    org.springframework.cloud.gateway: INFO
    com.vlz: DEBUG

app:
  frontend-url: ${FRONTEND_URL:http://localhost:3000}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  metrics:
    export:
      prometheus:
        enabled: true
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://${ZIPKIN_HOST:localhost}:9411/api/v2/spans

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
    display-request-duration: true
  api-docs:
    path: /v3/api-docs
